pipeline:
  identifier: Build_react_pipeline_sample_1689078012385
  name: Build react-pipeline-sample
  orgIdentifier: default
  projectIdentifier: sampleapp
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1688732447550
        repoName: lakshmanch2496/react-pipeline-sample
        build: <+input>
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: build app
                  spec:
                    shell: Sh
                    command: npm run build
                  timeout: ""
                  type: Run
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: <+input>
                    image: <+input>
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
